let handler = async(m, { conn }) => {
  await conn.sendFile(m.chat, pickRandom(ass), 'ass.gif', '', m)
}
handler.help = ['ass']
handler.tags = ['nsfw']
handler.command = /^ass$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = true
handler.private = false
handler.nsfw = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.register = true

module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

const ass = [
      'http://porngif.top/gif/zadky/0001.gif',
      'http://porngif.top/gif/zadky/0002.gif',
      'http://porngif.top/gif/zadky/0003.gif',
      'http://porngif.top/gif/zadky/0004.gif',
      'http://porngif.top/gif/zadky/0005.gif',
      'http://porngif.top/gif/zadky/0006.gif',
      'http://porngif.top/gif/zadky/0007.gif',
      'http://porngif.top/gif/zadky/0008.gif',
      'http://porngif.top/gif/zadky/0009.gif',
      'http://porngif.top/gif/zadky/0010.gif',
      'http://porngif.top/gif/zadky/0011.gif',
      'http://porngif.top/gif/zadky/0012.gif',
      'http://porngif.top/gif/zadky/0013.gif',
      'http://porngif.top/gif/zadky/0014.gif',
      'http://porngif.top/gif/zadky/0015.gif',
      'http://porngif.top/gif/zadky/0016.gif',
      'http://porngif.top/gif/zadky/0017.gif',
      'http://porngif.top/gif/zadky/0018.gif',
      'http://porngif.top/gif/zadky/0019.gif',
      'http://porngif.top/gif/zadky/0020.gif',
      'http://porngif.top/gif/zadky/0021.gif',
      'http://porngif.top/gif/zadky/0022.gif',
      'http://porngif.top/gif/zadky/0023.gif',
      'http://porngif.top/gif/zadky/0024.gif',
      'http://porngif.top/gif/zadky/0024.gif',
      'http://porngif.top/gif/zadky/0025.gif',
      'http://porngif.top/gif/zadky/0026.gif',
      'http://porngif.top/gif/zadky/0027.gif',
      'http://porngif.top/gif/zadky/0028.gif',
      'http://porngif.top/gif/zadky/0029.gif',
      'http://porngif.top/gif/zadky/0030.gif',
      'http://porngif.top/gif/zadky/0031.gif',
      'http://porngif.top/gif/zadky/0032.gif',
      'http://porngif.top/gif/zadky/0033.gif',
      'http://porngif.top/gif/zadky/0034.gif',
      'http://porngif.top/gif/zadky/0035.gif',
      'http://porngif.top/gif/zadky/0036.gif',
      'http://porngif.top/gif/zadky/0037.gif',
      'http://porngif.top/gif/zadky/0038.gif',
      'http://porngif.top/gif/zadky/0039.gif',
      'http://porngif.top/gif/zadky/0040.gif',
      'http://porngif.top/gif/zadky/0041.gif',
      'http://porngif.top/gif/zadky/0042.gif',
      'http://porngif.top/gif/zadky/0043.gif',
      'http://porngif.top/gif/zadky/0044.gif',
      'http://porngif.top/gif/zadky/0045.gif',
      'http://porngif.top/gif/zadky/0046.gif',
      'http://porngif.top/gif/zadky/0047.gif',
      'http://porngif.top/gif/zadky/0048.gif',
      'http://porngif.top/gif/zadky/0049.gif',
      'http://porngif.top/gif/zadky/0050.gif',
      'http://porngif.top/gif/zadky/0051.gif',
      'http://porngif.top/gif/zadky/0052.gif',
      'http://porngif.top/gif/zadky/0053.gif',
      'http://porngif.top/gif/zadky/0054.gif',
      'http://porngif.top/gif/zadky/0055.gif',
      'http://porngif.top/gif/zadky/0056.gif',
      'http://porngif.top/gif/zadky/0057.gif',
      'http://porngif.top/gif/zadky/0058.gif',
      'http://porngif.top/gif/zadky/0059.gif',
      'http://porngif.top/gif/zadky/0060.gif',
      'http://porngif.top/gif/zadky/0061.gif',
      'http://porngif.top/gif/zadky/0062.gif',
      'http://porngif.top/gif/zadky/0063.gif',
      'http://porngif.top/gif/zadky/0064.gif',
      'http://porngif.top/gif/zadky/0065.gif',
      'http://porngif.top/gif/zadky/0066.gif',
      'http://porngif.top/gif/zadky/0067.gif',
      'http://porngif.top/gif/zadky/0068.gif',
      'http://porngif.top/gif/zadky/0069.gif',
      'http://porngif.top/gif/zadky/0070.gif',
      'http://porngif.top/gif/zadky/0071.gif',
      'http://porngif.top/gif/zadky/0072.gif',
      'http://porngif.top/gif/zadky/0073.gif',
      'http://porngif.top/gif/zadky/0074.gif',
      'http://porngif.top/gif/zadky/0075.gif',
      'http://porngif.top/gif/zadky/0076.gif',
      'http://porngif.top/gif/zadky/0077.gif',
      'http://porngif.top/gif/zadky/0078.gif',
      'http://porngif.top/gif/zadky/0079.gif',
      'http://porngif.top/gif/zadky/0080.gif',
      'http://porngif.top/gif/zadky/0081.gif',
      'http://porngif.top/gif/zadky/0082.gif',
      'http://porngif.top/gif/zadky/0083.gif',
      'http://porngif.top/gif/zadky/0084.gif',
      'http://porngif.top/gif/zadky/0085.gif',
      'http://porngif.top/gif/zadky/0086.gif',
      'http://porngif.top/gif/zadky/0087.gif',
      'http://porngif.top/gif/zadky/0088.gif',
      'http://porngif.top/gif/zadky/0089.gif',
      'http://porngif.top/gif/zadky/0090.gif',
      'http://porngif.top/gif/zadky/0091.gif',
      'http://porngif.top/gif/zadky/0092.gif',
      'http://porngif.top/gif/zadky/0093.gif',
      'http://porngif.top/gif/zadky/0094.gif',
      'http://porngif.top/gif/zadky/0095.gif',
      'http://porngif.top/gif/zadky/0096.gif',
      'http://porngif.top/gif/zadky/0097.gif',
      'http://porngif.top/gif/zadky/0098.gif',
      'http://porngif.top/gif/zadky/0099.gif',
      'http://porngif.top/gif/zadky/0100.gif',
      'http://porngif.top/gif/zadky/0101.gif',
      'http://porngif.top/gif/zadky/0102.gif',
      'http://porngif.top/gif/zadky/0103.gif',
      'http://porngif.top/gif/zadky/0104.gif',
      'http://porngif.top/gif/zadky/0105.gif',
      'http://porngif.top/gif/zadky/0106.gif',
      'http://porngif.top/gif/zadky/0107.gif',
      'http://porngif.top/gif/zadky/0108.gif',
      'http://porngif.top/gif/zadky/0109.gif',
      'http://porngif.top/gif/zadky/0110.gif',
      'http://porngif.top/gif/zadky/0111.gif',
      'http://porngif.top/gif/zadky/0112.gif',
      'http://porngif.top/gif/zadky/0113.gif',
      'http://porngif.top/gif/zadky/0114.gif',
      'http://porngif.top/gif/zadky/0115.gif',
      'http://porngif.top/gif/zadky/0116.gif',
      'http://porngif.top/gif/zadky/0117.gif',
      'http://porngif.top/gif/zadky/0118.gif',
      'http://porngif.top/gif/zadky/0119.gif',
      'http://porngif.top/gif/zadky/0120.gif',
      'http://porngif.top/gif/zadky/0121.gif',
      'http://porngif.top/gif/zadky/0122.gif',
      'http://porngif.top/gif/zadky/0123.gif',
      'http://porngif.top/gif/zadky/0124.gif',
      'http://porngif.top/gif/zadky/0125.gif',
      'http://porngif.top/gif/zadky/0126.gif',
      'http://porngif.top/gif/zadky/0127.gif',
      'http://porngif.top/gif/zadky/0128.gif',
      'http://porngif.top/gif/zadky/0129.gif',
      'http://porngif.top/gif/zadky/0130.gif',
      'http://porngif.top/gif/zadky/0131.gif',
      'http://porngif.top/gif/zadky/0132.gif',
      'http://porngif.top/gif/zadky/0133.gif',
      'http://porngif.top/gif/zadky/0134.gif',
      'http://porngif.top/gif/zadky/0135.gif',
      'http://porngif.top/gif/zadky/0136.gif',
      'http://porngif.top/gif/zadky/0137.gif',
      'http://porngif.top/gif/zadky/0138.gif',
      'http://porngif.top/gif/zadky/0139.gif',
      'http://porngif.top/gif/zadky/0140.gif',
      'http://porngif.top/gif/zadky/0141.gif',
      'http://porngif.top/gif/zadky/0142.gif',
      'http://porngif.top/gif/zadky/0143.gif',
      'http://porngif.top/gif/zadky/0144.gif',
      'http://porngif.top/gif/zadky/0145.gif',
      'http://porngif.top/gif/zadky/0146.gif',
      'http://porngif.top/gif/zadky/0147.gif',
      'http://porngif.top/gif/zadky/0148.gif',
      'http://porngif.top/gif/zadky/0149.gif',
      'http://porngif.top/gif/zadky/0150.gif',
      'http://porngif.top/gif/zadky/0151.gif',
      'http://porngif.top/gif/zadky/0152.gif',
      'http://porngif.top/gif/zadky/0153.gif',
      'http://porngif.top/gif/zadky/0154.gif',
      'http://porngif.top/gif/zadky/0155.gif',
      'http://porngif.top/gif/zadky/0156.gif',
      'http://porngif.top/gif/zadky/0157.gif',
      'http://porngif.top/gif/zadky/0158.gif',
      'http://porngif.top/gif/zadky/0159.gif',
      'http://porngif.top/gif/zadky/0160.gif',
      'http://porngif.top/gif/zadky/0161.gif',
      'http://porngif.top/gif/zadky/0162.gif',
      'http://porngif.top/gif/zadky/0163.gif',
      'http://porngif.top/gif/zadky/0164.gif',
      'http://porngif.top/gif/zadky/0165.gif',
      'http://porngif.top/gif/zadky/0166.gif',
      'http://porngif.top/gif/zadky/0167.gif',
      'http://porngif.top/gif/zadky/0168.gif',
      'http://porngif.top/gif/zadky/0169.gif',
      'http://porngif.top/gif/zadky/0170.gif',
      'http://porngif.top/gif/zadky/0171.gif',
      'http://porngif.top/gif/zadky/0172.gif',
      'http://porngif.top/gif/zadky/0173.gif',
      'http://porngif.top/gif/zadky/0174.gif',
      'http://porngif.top/gif/zadky/0175.gif',
      'http://porngif.top/gif/zadky/0176.gif',
      'http://porngif.top/gif/zadky/0177.gif',
      'http://porngif.top/gif/zadky/0178.gif',
      'http://porngif.top/gif/zadky/0179.gif',
      'http://porngif.top/gif/zadky/0180.gif',
      'http://porngif.top/gif/zadky/0181.gif',
      'http://porngif.top/gif/zadky/0182.gif',
      'http://porngif.top/gif/zadky/0183.gif',
      'http://porngif.top/gif/zadky/0184.gif',
      'http://porngif.top/gif/zadky/0185.gif',
      'http://porngif.top/gif/zadky/0186.gif']
